CREATE TABLE USUARIOS (
  usuario_id SERIAL NOT NULL,
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(300) NOT NULL,
  activo BOOLEAN NOT NULL,
  cuenta_expirada BOOLEAN NOT NULL,
  cuenta_bloqueada BOOLEAN NOT NULL,
  credenciales_expiradas BOOLEAN NOT NULL
);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY(usuario_id);

CREATE TABLE ROLES (
    rol_id SERIAL NOT NULL,
    rol VARCHAR(100) NOT NULL,
    rol_bonito VARCHAR(100) NOT NULL
);

ALTER TABLE ROLES ADD CONSTRAINT PK_ROLES PRIMARY KEY(rol_id);

CREATE TABLE USUARIOS_ROLES (
    usuario_rol_id SERIAL NOT NULL,
    rol_id INT NOT NULL,
    usuario_id INT NOT NULL
);

ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT PK_USUARIOS_ROLES PRIMARY KEY(usuario_rol_id);

ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT FK_USUARIOS FOREIGN KEY (usuario_id) REFERENCES USUARIOS(usuario_id);
ALTER TABLE USUARIOS_ROLES ADD CONSTRAINT FK_ROLES FOREIGN KEY (rol_id) REFERENCES ROLES(rol_id);


INSERT INTO ROLES(rol, rol_bonito) VALUES('ADMIN', 'Administrador');
INSERT INTO ROLES(rol, rol_bonito) VALUES('USER', 'Usuario común');
